### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by chrisanthropic** [chrisanthropic/Open-Publisher#3]
Create a Dockerfile that includes all of the dependencies so we can make 'install' and use easier for those who want to use docker.

**Comment by lgoldstien** [comment]
As per the pull request from the other day, I have done a little work on dockerising this application, I'll push some of my work up later on for you to have a look through.

I'm liking the idea to put all the scripts into a rakefile, this will make the docker workflow much simpler for end user types :-)

**Comment by chrisanthropic** [comment]
Thanks man, I just merged the new Rakefile. Running it will spit out how to use it and what commands do what etc.

The next major hurdle (for me) before I feel comfortable tackling the Docker build is issue #2 / finding a way to have good FREE LaTeX fallback fonts for those without expensive ass Adobe fonts installed.

**Comment by chrisanthropic** [comment]
Docker branch moved to master and documentation updated.

The docker image is fucking huge (3.5 GB) so there's still a LOT of work to do to shrink it as much as possible.
